### ISSUE TITLE
selection weight functions

### ISSUE THREAD

**Issue by steffilazerte** [ARUtools/ARUtools#14]
This issue is a placeholder for discussions regarding the section functions including `calc_sel_pr()`, `gen_dens_sel_simulation()` and ~~`fun_aru_samp()`~~ [will move that to it's own issue].

**General**
- Do these ideas for new function names make sense?
  - `calc_sel_pr()` -> `calc_selection_probs()`
  - `gen_dens_sel_simulation()` -> `simulate_selection_probs()`
  - `fun_aru_samp()` -> `sample_recordings()` 
 - These functions use NSE for column names, but elsewhere in ARUtools we've used quoted column names. I think we should be consistent, or at least have a consistent rule.
    - We could use all character column names or all NSE column names. Although since some of the column name definitions are for columns in data files (not in data frames), my preference would be to use all character column names.
    - We could also use character column names specifically for when data is coming from a data file, and NSE evaluation every where else? 
- There are some deprecated methods and warnings (especially in `gen_dens_sel_simulation()`), I suggest removing these and starting clean.
- `parms`
  - I'd like to make this argument `params`
  - `default_selection_parameters` is good, but I think a helper function would be even more useful for defining parameters, it could be set with the defaults and then users only have to change the pieces they need
  - Should this [helper function](https://github.com/dhope/ARUtools/blob/e786b2e787af99418edfb434298e623513b0fe16/R/CalcSelPr.R#L188-L221) use the defaults from `calc_sel_pr()` or the ones defined in `default_selection_parameters`?

**Comment by dhope** [comment]
I think the new function names sound like a big improvement.

I prefer using NSE just because Rstudio autofills column names, but I agree it should be consistent. Lets try your suggestion of NSE when it is drawing from a column and character when drawing from the data. I'll try to get some feedback on this at the workshop next month and see if the current approach is too confusing.

Yes, fine to drop old methods and warnings. Those warnings were mostly for myself when I made a big change, but can drop now.

`parms` sounds like cheese. Yes, thanks for catching that. 

A helper function sounds good for this situation. I find they work well with the regex functions and this is another one of those cases where it seems like it would really help the user. Good idea. I wonder if getting folks to enter dates using ymd would be more user friendly than current day of year. Could we use a call from `simulate_selection_probs()` to generate the `params`?

For defaults, I'm currently using the following for most of my northern work. I'm almost thinking to remove defaults as this is something folks should think about.

I'll actually put my current workflow here as I've tried to simpify it a bit by doing dawn and dusk selection at the same time.

```
parms <- list(Dawn = list(min_range = c(-70, 240),
                          doy_range = c(120, lubridate::yday(lubridate::ymd("2021-07-20"))),
                          mean_min = 30, sd_min = 60,
                          mean_doy = lubridate::yday(lubridate::ymd("2021-06-10")),
                          sd_doy = 20,off=0,
                          log_ = TRUE, fun = "norm"),
              Dusk = 
                list(min_range = c(-40,120),
                     doy_range =  c(120, lubridate::yday(lubridate::ymd("2021-07-20"))),
                     mean_min = 30, sd_min = 120,
                     mean_doy = lubridate::yday(lubridate::ymd("2021-06-10")),
                     sd_doy = 60,off= 30,
                     log_ = T, fun = "norm"))


# Check selection probabilty settings

ARUtools::gen_dens_sel_simulation(parms = parms$Dawn)
ARUtools::gen_dens_sel_simulation(parms = parms$Dusk)




full_selection_probs <- 
  files_for_selection |> 
  filter(doy<=lubridate::yday(lubridate::ymd("2021-07-20"))) %>% 
  nest_by(Time_period, year) %>% 
  rowwise() %>% 
  mutate(sel_pr =  list(calc_sel_pr(.data = data,
                                    ARU_ID_col = site_id, 
                                    min_col = t2se, 
                                    day_col = doy,
                                    parms = parms[[Time_period]]) ) ) %>% 
  dplyr::select(-data) %>% 
  unnest(sel_pr) %>% 
  mutate(Selection_group = glue::glue("{site_id}__{year}__{Time_period}"))


# Set sample sizes
samples <-  tibble(Selection_group = unique(full_selection_probs$Selection_group),
                   n_samples = ifelse(grepl("Dawn", Selection_group), 31, 16),
                   n_os = ifelse(grepl("Dawn", Selection_group), floor(n_samples*1/3), floor(n_samples*1/4)))
SampleSize <- 
  full_selection_probs |> 
  count(site_id, Selection_group) |> 
  
  left_join(samples, by = join_by( Selection_group)) |> 
  mutate(n_os = pmax(0,pmin(n-n_samples, round(n_samples/3))),
         N= pmin(n_samples, n) ) 

# Select Samples
grts_res <- fun_aru_samp(full_selection_probs, 
                         N = SampleSize,
                         strat_ = "Selection_group",
                         seed = 911, selprob_id = "psel_normalized",
                         x = 'doy',y = 't2se')

```

**Comment by steffilazerte** [comment]
Just to clarify...
> Could we use a call from simulate_selection_probs() to generate the params?

So the idea would be to use simulate_selection_probs() as both a function to create the probabilities and to explore them? I think we can do that :D

**Comment by dhope** [comment]
I was more thinking of using `sumulate_selection_probs()` as a tool to create the parameters to input into `params`, but also generate the visual output. So instead of starting from scratch on a helper function, use `gen_dens_sel_simulation` to allow visual exploration of the parameters, but also return a properly formatted parameter list. Could you have the return for the function be `params` and the plotting be a side effect of the function?

**Comment by dhope** [comment]
Great. Very likely not clearly read on my end either.

**Comment by steffilazerte** [comment]
Okay! Making progress. Thanks for your updated workflow, that's really helpful for thinking about how to streamline things.

- `simulate_selection_probs()` 
    - checks the parameter options
    - prints a plot and returns parameters (if `return_param = TRUE)
    - parameter arguments are standardized (so `mean_min` is now `min_mean` to match `min_range` etc.)
    - users can supply `day_range` and `day_mean` as Date class, DOY numbers or Date-like character (e.g., "2020-01-01"). Note that this doesn't apply to `day_sd` as that would make no sense, so that still has to be a number
    - I used your current values for the defaults. I agree that people should think about this, but as you're probably the one who will use it the most, let's make it easier for you. Having sensible defaults also helps people get started.

- `calc_selection_probs()`
  - checks the parameter options (in case someone skips `simulate_selection_probs()`)
  - uses `site_id` rather than `aru_id` by default
  - catches situations where there are no recordings within the date/min limits
  - allows users to use a `date`, `date_time` or `doy` column (converts to DOY if not already DOY)
  - returns a minimal data frame with only the required columns and added selection probabilities
 
**Questions**
- Are there parameter combinations that can't/shouldn't happen?
    - i.e. would it make sense to have a mean outside the range? i.e. min_range = c(-30, 60) and min_mean = 90?
    - if these kinds of restrictions exist, I'll add these checks to the functions
- the `off` (or `offset`) only applies to the lognorm function 
    - should this be set automatically as `min(min_range) + 1`? 
    - I added a message saying that `offset` is ignored when the selection function is not `lognorm`, make sense?
- Do we want to standardize the language with BASSr? In BASSr, we refer to inclusion probabilities, in ARUtools, it's a bit of both... should we use inc_probs here? i.e., `calc_inc_probs`, `simulate_inc_probs`, and then the names of returned data could be `inc_pr_tod`, `inc_pr_doy` etc.
- With the returned data, what does `tod` mean?

(Note: I'll deal with the column name specifications at the end, and will do it for all the functions at once #15)

**Comment by dhope** [comment]
Sounds good. 
To your specific Questions:

> Are there parameter combinations that can't/shouldn't happen? 
- SD should be positive and `fun` should be one of the options, but otherwise pretty open.
- putting the mean outside the range might be relevant if you wanted a one-sided distribution to selection.
> the off (or offset) only applies to the lognorm function
> should this be set automatically as min(min_range) + 1?
> I added a message saying that offset is ignored when the selection function is not lognorm, make sense?
- Yeah, there has to be a min on offset or it will cause errors. The way it is coded it looks like it has to be mean_min>=off. Default should be zero.
> Do we want to standardize the language with BASSr? In BASSr, we refer to inclusion probabilities, in ARUtools, it's a bit of both... > should we use inc_probs here? i.e., calc_inc_probs, simulate_inc_probs, and then the names of returned data could be inc_pr_tod, > inc_pr_doy etc.
- Sure, I guess it makes sense to standardize. I'm not a big fan of inclusion probabilities here (selection weights is probably more accurate), but probably easier to stick with what we've done in BASSr.
> With the returned data, what does tod mean?
- Time of Day. Looks a bit inconsistent with min on input. Could be psel_min.

**Comment by steffilazerte** [comment]
Okay! Thanks for the feedback @dhope 
- I added limits to SD (must be positive)
- I renamed `tod` to `min`
- I renamed things to `selection_weights`. Let's be accurate for now, if we need to change it we can. (Or we can change it in BASSr?) (in light of this, I also simplified `simulate_selection_weights()` to `sim_selection_weights()` so the function names don't get too ridiculously long 😁 )
    - Alternatively, perhaps we could just go with `selections`? `calc_selections()`, `simulate_selections()`? Might simplify the names and then avoid the terminology issue...?

And for the offset, just to make sure I understand: 
1. This only applies with lognorm functions (so it's ignored otherwise)
2. By default it should be zero
3. I added a check such that if the offset isn't enough to bring the minimum values above 0, you get an error, is this accurate?

```
Error:
! If `selection_fun = 'lognorm'` and any `min` values are less than 0
you must provide an `offset` large enough to ensure all values are greater than 0.
```

**Comment by dhope** [comment]
Thanks for this. I think `selection_weights` is fine for now. Simplifying it further seems like it might get a bit more confusing.

For the offset. I looked back at it and am failing to see much use case for `lognorm` anymore. The check you've you created  sounds like it will avoid all-zero selection weights, which was the issue before. I'd suggest leave it for now as this is a low use case and I might just drop it completely down the line.
